Repository wecode-bootcamp-korea/36-1st-BIKINGS-frontend, pull requests merged in 2022-08, with the labels that each got.

#11 [36기 권영준] Variable.scss 설정
  src/styles/variable.scss
Labels: 완료

#15 [36기 권영준] TopBtn ui 기능구현 완성
  src/Router.js
  src/components/TopBtn/TopBtn.js
  src/components/TopBtn/TopBtn.scss
Labels: 멘토 리뷰 요청

#14 [36기 이주영]Feature/footer
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Nav/Nav.js
  src/pages/Main/Main.js
Labels: 멘토 리뷰 요청

#13 [36기 문보성] Nav 완성
  public/images/blog.png
  public/images/blog2.png
  public/images/blogger.png
  public/images/facebook.png
  public/images/facebook1.png
  public/images/facebook2.png
  public/images/instagram.png
  public/images/instagram1.png
  public/images/instagram2.png
  public/images/loupe.png
  public/images/shopping-cart.png
  public/images/shopping-cart1.png
  public/images/shopping-cart2.png
  public/images/shopping-cart3.png
  public/images/youtube.png
  public/images/youtube1.png
  public/images/youtube2.png
  src/Router.js
  src/components/Nav/DropDown.js
  src/components/Nav/DropDown.scss
  src/components/Nav/DropDownData.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/config.js
  src/pages/Main/Login/LoginInput.js
  src/pages/Main/Login/LoginInput.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#17 [36기 권영준] 전역적으로 사용될 모달 구현
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
Labels: 멘토 리뷰 요청

#4 [36기 권영준] ADD: product Page UI , 기능 구현
  public/data/CheckList.json
  public/images/ProductTopImg.png
  public/images/testImg.png
  src/Router.js
  src/config.js
  src/pages/Main/Inner/InnerList/InnerList.js
  src/pages/Main/Inner/InnerList/InnerList.scss
  src/pages/Main/Main.scss
  src/pages/Product/BycleInfo/BycleInfo.js
  src/pages/Product/BycleInfo/BycleInfo.scss
  src/pages/Product/Product.js
  src/pages/Product/Product.scss
  src/pages/Product/ProductCheckList/ProductCheackList.js
  src/pages/Product/ProductCheckList/ProductCheackList.scss
Labels: 멘토 리뷰 요청

#12 [36기 문보성] login 및 signup 리뷰 반영
  src/components/Modal/Modal.js
  src/components/Nav/Nav.js
  src/pages/Main/Login/Login.js
  src/pages/Main/Login/Login.scss
  src/pages/Main/Login/LoginInput.js
  src/pages/Main/Login/LoginInput.scss
Labels: 멘토 리뷰 요청

#7 [36기 이주영]ADD: product_detail 페이지 main section layout 완료
  package-lock.json
  package.json
  public/images/마켓컬리.png
  public/index.html
  src/Router.js
  src/components/Nav/Nav.js
  src/config.js
  src/pages/ProductDetail/Carts/Carts.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/Tags/Tags.js
  src/pages/ProductDetail/Tags/Tags.scss
Labels: 멘토 리뷰 요청

#10 [36기 이주영] ADD: Feature/carts 장바구니 UI 및 modal 기능 구현
  public/data/data.json
  public/images/카트.png
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/config.js
  src/index.js
  src/pages/Product/BycleInfo/BycleInfo.js
  src/pages/Product/Product.js
  src/pages/ProductDetail/Carts/Carts.js
  src/pages/ProductDetail/Carts/Carts.scss
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/Tags/Tags.scss
Labels: 멘토 리뷰 요청

#21 [36기 이주영][main] footer 최종 수정을 위한 브랜치 생성후 완료
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#24 [36기 권영준] 전체 코드 리팩토링
  src/Function.js
  src/components/Nav/DropDown/DropDown.js
  src/components/Nav/DropDown/DropDown.scss
  src/components/Nav/DropDown/DropDownData.js
  src/components/Nav/Nav.js
  src/components/TopBtn/TopBtn.js
  src/components/TopBtn/TopBtn.scss
  src/config.js
  src/pages/Main/Inner/Inner.js
  src/pages/Main/Login/Login.js
  src/pages/Main/Login/LoginInput.js
  src/pages/Main/Main.js
  src/pages/Main/Signup/Signup.js
  src/pages/Main/Signup/Signup.scss
  src/pages/Product/Product.js
  src/pages/Product/ProductCheckList/ProductCheckList.js
  src/pages/Product/ProductCheckList/ProductCheckList.scss
  src/pages/ProductDetail/Carts/Carts.js
Labels: 수정 요청

#23 [36기 이주영]fix myPage UI, refactoring and complete
  src/pages/Mypage/Mypage.js
  src/pages/Mypage/Mypage.scss
  src/pages/Mypage/NoOrder.js
  src/pages/Mypage/NoOrder.scss
  src/pages/Mypage/OrderData/OrderData.js
  src/pages/Mypage/OrderData/OrderData.scss
  src/pages/Mypage/UserInfo.js
  src/pages/Mypage/UserInfo.scss
  src/pages/Mypage/UserInfo/DeleteId/DeleteId.js
  src/pages/Mypage/UserInfo/DeleteId/DeleteId.scss
  src/pages/Mypage/UserInfo/UserInfo.js
  src/pages/Mypage/UserInfo/UserInfo.scss
Labels: 멘토 리뷰 요청

#8 [36기 권영준] pricePage 구현
  public/data/priceData.json
  public/images/test.png
  src/Router.js
  src/components/Nav/Nav.js
  src/pages/Price/Price.js
  src/pages/Price/Price.scss
  src/pages/Price/PriceContent.js
  src/pages/Price/PriceContent.scss
  src/pages/Product/Product.js
  src/pages/ProductDetail/Carts/Carts.js
  src/pages/ProductDetail/ProductDetail.js
Labels: 멘토 리뷰 요청
